export default {
    slides: [
        {
            id: 2,
            title: "1",
            description: null,
            image: {
                id: 45,
                name: "1.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_1.jpg",
                        hash: "thumbnail_1_a1a92ffe12",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 10.55,
                        path: null,
                        url: "/uploads/thumbnail_1_a1a92ffe12.jpg",
                    },
                    small: {
                        name: "small_1.jpg",
                        hash: "small_1_a1a92ffe12",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 57.66,
                        path: null,
                        url: "/uploads/small_1_a1a92ffe12.jpg",
                    },
                },
                hash: "1_a1a92ffe12",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 130.09,
                url: "/uploads/1_a1a92ffe12.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:52:21.328Z",
                updated_at: "2020-10-21T16:52:21.355Z",
            },
        },
        {
            id: 4,
            title: "Tytuł ",
            description:
                "Krótki opis (opcjonalny)\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vestibulum velit fringilla augue malesuada, in interdum lacus finibus. Ut massa nisi, tincidunt non laoreet quis, dictum ac leo. Cras tellus est, vehicula tincidunt neque ac, ultrices iaculis eros. Suspendisse potenti. Mauris facilisis nibh ac nisl volutpat elementum. Curabitur finibus diam non lorem fringilla venenatis. Fusce neque dolor, aliquam nec turpis ac, interdum rutrum metus. In ut est dolor. Etiam rutrum ut diam eu malesuada. Etiam interdum massa ut porttitor maximus. Sed lacinia ut est at molestie.\n\n",
            image: {
                id: 30,
                name: "2.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_2.jpg",
                        hash: "thumbnail_2_3abd5d9800",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 6.37,
                        path: null,
                        url: "/uploads/thumbnail_2_3abd5d9800.jpg",
                    },
                    small: {
                        name: "small_2.jpg",
                        hash: "small_2_3abd5d9800",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 27.97,
                        path: null,
                        url: "/uploads/small_2_3abd5d9800.jpg",
                    },
                },
                hash: "2_3abd5d9800",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 53.69,
                url: "/uploads/2_3abd5d9800.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:41:22.501Z",
                updated_at: "2020-10-21T16:41:22.531Z",
            },
        },
        {
            id: 3,
            title: "3",
            description: null,
            image: {
                id: 31,
                name: "3.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_3.jpg",
                        hash: "thumbnail_3_cbee420db8",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 10.13,
                        path: null,
                        url: "/uploads/thumbnail_3_cbee420db8.jpg",
                    },
                    small: {
                        name: "small_3.jpg",
                        hash: "small_3_cbee420db8",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 52.87,
                        path: null,
                        url: "/uploads/small_3_cbee420db8.jpg",
                    },
                },
                hash: "3_cbee420db8",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 119.04,
                url: "/uploads/3_cbee420db8.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:41:32.239Z",
                updated_at: "2020-10-21T16:41:32.265Z",
            },
        },
        {
            id: 5,
            title: "4",
            description: null,
            image: {
                id: 41,
                name: "4.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_4.jpg",
                        hash: "thumbnail_4_7c3ba6b866",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 11.06,
                        path: null,
                        url: "/uploads/thumbnail_4_7c3ba6b866.jpg",
                    },
                    small: {
                        name: "small_4.jpg",
                        hash: "small_4_7c3ba6b866",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 56.98,
                        path: null,
                        url: "/uploads/small_4_7c3ba6b866.jpg",
                    },
                },
                hash: "4_7c3ba6b866",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 123.11,
                url: "/uploads/4_7c3ba6b866.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:54.352Z",
                updated_at: "2020-10-21T16:42:54.588Z",
            },
        },
        {
            id: 14,
            title: "5",
            description: null,
            image: {
                id: 39,
                name: "5.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 562,
                formats: {
                    thumbnail: {
                        name: "thumbnail_5.jpg",
                        hash: "thumbnail_5_755962f44f",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 12.02,
                        path: null,
                        url: "/uploads/thumbnail_5_755962f44f.jpg",
                    },
                    small: {
                        name: "small_5.jpg",
                        hash: "small_5_755962f44f",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 57.31,
                        path: null,
                        url: "/uploads/small_5_755962f44f.jpg",
                    },
                },
                hash: "5_755962f44f",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 113.35,
                url: "/uploads/5_755962f44f.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:54.316Z",
                updated_at: "2020-10-21T16:42:54.523Z",
            },
        },
        {
            id: 15,
            title: "6",
            description: null,
            image: {
                id: 42,
                name: "6.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_6.jpg",
                        hash: "thumbnail_6_1fc4cbe565",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 10.1,
                        path: null,
                        url: "/uploads/thumbnail_6_1fc4cbe565.jpg",
                    },
                    small: {
                        name: "small_6.jpg",
                        hash: "small_6_1fc4cbe565",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 49.87,
                        path: null,
                        url: "/uploads/small_6_1fc4cbe565.jpg",
                    },
                },
                hash: "6_1fc4cbe565",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 99.25,
                url: "/uploads/6_1fc4cbe565.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:54.373Z",
                updated_at: "2020-10-21T16:42:54.629Z",
            },
        },
        {
            id: 6,
            title: "7",
            description: null,
            image: {
                id: 40,
                name: "7.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_7.jpg",
                        hash: "thumbnail_7_0720d8b82b",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 12.54,
                        path: null,
                        url: "/uploads/thumbnail_7_0720d8b82b.jpg",
                    },
                    small: {
                        name: "small_7.jpg",
                        hash: "small_7_0720d8b82b",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 57.97,
                        path: null,
                        url: "/uploads/small_7_0720d8b82b.jpg",
                    },
                },
                hash: "7_0720d8b82b",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 119.6,
                url: "/uploads/7_0720d8b82b.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:54.337Z",
                updated_at: "2020-10-21T16:42:54.555Z",
            },
        },
        {
            id: 7,
            title: "8",
            description: null,
            image: {
                id: 38,
                name: "8.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_8.jpg",
                        hash: "thumbnail_8_f919ffb4ab",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 11.18,
                        path: null,
                        url: "/uploads/thumbnail_8_f919ffb4ab.jpg",
                    },
                    small: {
                        name: "small_8.jpg",
                        hash: "small_8_f919ffb4ab",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 54.04,
                        path: null,
                        url: "/uploads/small_8_f919ffb4ab.jpg",
                    },
                },
                hash: "8_f919ffb4ab",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 116.75,
                url: "/uploads/8_f919ffb4ab.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:54.290Z",
                updated_at: "2020-10-21T16:42:54.485Z",
            },
        },
        {
            id: 8,
            title: "9",
            description: null,
            image: {
                id: 37,
                name: "9.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_9.jpg",
                        hash: "thumbnail_9_460aad778c",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 13.7,
                        path: null,
                        url: "/uploads/thumbnail_9_460aad778c.jpg",
                    },
                    small: {
                        name: "small_9.jpg",
                        hash: "small_9_460aad778c",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 69.53,
                        path: null,
                        url: "/uploads/small_9_460aad778c.jpg",
                    },
                },
                hash: "9_460aad778c",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 136.76,
                url: "/uploads/9_460aad778c.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:53.951Z",
                updated_at: "2020-10-21T16:42:54.098Z",
            },
        },
        {
            id: 9,
            title: "10",
            description: null,
            image: {
                id: 44,
                name: "10.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_10.jpg",
                        hash: "thumbnail_10_13e78db86c",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 14.89,
                        path: null,
                        url: "/uploads/thumbnail_10_13e78db86c.jpg",
                    },
                    small: {
                        name: "small_10.jpg",
                        hash: "small_10_13e78db86c",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 67.63,
                        path: null,
                        url: "/uploads/small_10_13e78db86c.jpg",
                    },
                },
                hash: "10_13e78db86c",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 126.1,
                url: "/uploads/10_13e78db86c.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:45:22.889Z",
                updated_at: "2020-10-21T16:45:22.914Z",
            },
        },
        {
            id: 10,
            title: "11",
            description: null,
            image: {
                id: 36,
                name: "11.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_11.jpg",
                        hash: "thumbnail_11_db92296ffb",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 10.57,
                        path: null,
                        url: "/uploads/thumbnail_11_db92296ffb.jpg",
                    },
                    small: {
                        name: "small_11.jpg",
                        hash: "small_11_db92296ffb",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 51.81,
                        path: null,
                        url: "/uploads/small_11_db92296ffb.jpg",
                    },
                },
                hash: "11_db92296ffb",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 112.26,
                url: "/uploads/11_db92296ffb.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:53.939Z",
                updated_at: "2020-10-21T16:42:54.072Z",
            },
        },
        {
            id: 11,
            title: "12",
            description: null,
            image: {
                id: 35,
                name: "12.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_12.jpg",
                        hash: "thumbnail_12_cce6621a89",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 11.59,
                        path: null,
                        url: "/uploads/thumbnail_12_cce6621a89.jpg",
                    },
                    small: {
                        name: "small_12.jpg",
                        hash: "small_12_cce6621a89",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 57.26,
                        path: null,
                        url: "/uploads/small_12_cce6621a89.jpg",
                    },
                },
                hash: "12_cce6621a89",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 122.66,
                url: "/uploads/12_cce6621a89.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:53.922Z",
                updated_at: "2020-10-21T16:42:54.051Z",
            },
        },
        {
            id: 12,
            title: "13",
            description: null,
            image: {
                id: 47,
                name: "13.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_13.jpg",
                        hash: "thumbnail_13_4044bdcabc",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 10.38,
                        path: null,
                        url: "/uploads/thumbnail_13_4044bdcabc.jpg",
                    },
                    small: {
                        name: "small_13.jpg",
                        hash: "small_13_4044bdcabc",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 48.57,
                        path: null,
                        url: "/uploads/small_13_4044bdcabc.jpg",
                    },
                },
                hash: "13_4044bdcabc",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 101.25,
                url: "/uploads/13_4044bdcabc.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:53:57.193Z",
                updated_at: "2020-10-21T16:53:57.221Z",
            },
        },
        {
            id: 13,
            title: "14",
            description: null,
            image: {
                id: 34,
                name: "14.jpg",
                alternativeText: "",
                caption: "",
                width: 750,
                height: 563,
                formats: {
                    thumbnail: {
                        name: "thumbnail_14.jpg",
                        hash: "thumbnail_14_cbbe2a73b3",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 208,
                        height: 156,
                        size: 12.06,
                        path: null,
                        url: "/uploads/thumbnail_14_cbbe2a73b3.jpg",
                    },
                    small: {
                        name: "small_14.jpg",
                        hash: "small_14_cbbe2a73b3",
                        ext: ".jpg",
                        mime: "image/jpeg",
                        width: 500,
                        height: 375,
                        size: 61.24,
                        path: null,
                        url: "/uploads/small_14_cbbe2a73b3.jpg",
                    },
                },
                hash: "14_cbbe2a73b3",
                ext: ".jpg",
                mime: "image/jpeg",
                size: 136.96,
                url: "/uploads/14_cbbe2a73b3.jpg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                created_by: 1,
                updated_by: 1,
                created_at: "2020-10-21T16:42:53.907Z",
                updated_at: "2020-10-21T16:42:54.028Z",
            },
        },
    ],
    loaded: false,
    mainText: {
        id: 2,
        Opis:
            "<p>Firma wykonawcza <strong>GARDEN MASTER</strong> powstała w 2017 r z podziału spółki GARDENA, która istnieje na rynku od sierpnia 1990 r.</p><p>Firmę tworzy zespół projektowy architektów krajobrazu i igrodników oraz doświadczone ekipy wykonawcze. Działamy na terenie całego kraju. Posiadamy także odpowiedni potencjał materiałowy i sprzętowy do wykonywania nawet najtrudniejszych zadań: własny transport samochodami samowyładowczymi, koparko-ładowarki, koparki, ciągniki, mikrociągniki, siewniki, hydrosiewnik, pilarki, świdry, kosy spalinowe, kosiarki i inne. Dzięki współpracy z najlepszymi szkółkami oferujemy atrakcyjny materiał roślinny (w tym rośliny antysmogowe).</p><p>Członkowie naszej kadry są absolwentami Uniwersytetu Rolniczego i Politechniki Krakowskiej.<br>Posiadamy następujące uprawnienia:</p><ul><li>Rzeczoznawcy w zakresie projektowania terenów zieleni, budowy i konserwacji terenów zieleni, ochrony środowiska</li><li>Inspektor Nadzoru Terenów Zieleni</li><li>Gospodarz Terenów Zieleni</li><li>Pilarz Drzew Ozdobnych II stopnia NOT</li></ul><p>Główny Projektant jest również członkiem Polskiego Towarzystwa Chirurgów Drzew, biegłym sądowym przy Sądzie Okręgowym w Nowym Sączu w zakresie ogrodnictwa i architektury krajobrazu oraz wykładowcą do spraw projektowania, budowy i urządzania terenów zieleni w ośrodku szkoleniowym kadry instruktorskiej i inspektorskiej w SITO/NOT Oddział Rzeszów.</p>",
        created_by: {
            id: 1,
            firstname: "Michał",
            lastname: "Kadzik",
            username: null,
        },
        updated_by: {
            id: 1,
            firstname: "Michał",
            lastname: "Kadzik",
            username: null,
        },
        created_at: "2020-10-21T13:42:04.983Z",
        updated_at: "2020-10-21T13:42:04.991Z",
    },
    instagramPosts: [
        {
            id: 1,
            Link: "https://www.instagram.com/p/CFwdqNtlB09",
        },
        {
            id: 2,
            Link: "https://www.instagram.com/p/CDlYsGUJhRe",
        },
        {
            id: 3,
            Link: "https://www.instagram.com/p/B_VF8-VpTQh",
        },
        {
            id: 4,
            Link: "https://www.instagram.com/p/B8gUUunJZ-q",
        },
    ],
};
